name: abwaab_practice
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  intl: any
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  sizer: ^2.0.15
  super_tooltip: ^2.0.8
  syncfusion_flutter_charts: ^26.2.4
  syncfusion_flutter_core: ^26.2.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_animate: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/


  # example:
  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Bold.ttf
        - asset: assets/fonts/Dubai-Medium.ttf
        - asset: assets/fonts/Dubai-Regular.ttf
        - asset: assets/fonts/Dubai-Light.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

